name: "Notify"
description: "Notify"

inputs:
  telegram-bot-token:
    description: "Telegram Bot Token"
    required: true
  telegram-chat-id:
    description: "Telegram Chat ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Telegram Notification
      uses: actions/github-script@v6
      id: telegram-notification
      if: always()
      with:
        result-encoding: string
        retries: 3
        script: |
          const jobStatus = '${{ job.status }}'
          const workflowName = '${{ github.workflow }}'
          const actionName = '${{ github.action }}'
          const botToken = '${{ inputs.telegram-bot-token }}'
          const chatId = '${{ inputs.telegram-chat-id }}'
          const url = `https://api.telegram.org/bot${botToken}/sendMessage`
          const symbol = {
            success: '✅',
            failure: '❌',
            cancelled: '❕',
          }[jobStatus] || '❔'
          let message = `${symbol} <a href="${{ github.event.repository.html_url }}">${{ github.repository }}</a>
          <b>Workflow:</b> ${workflowName}
          <b>Action Run:</b> <a href="${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}">${{ github.run_id }}</a>
          <b>Status:</b> <i>${jobStatus}</i>`
          console.log(`Sending Telegram Notification: ${message}`)
          fetch(url, {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({
              chat_id: chatId,
              text: message,
              parse_mode: 'HTML'
            })
          }).then((response) => {
            if (response.status >= 400) {
              throw new Error(response.statusText)
            }
            return response.json()
          }).then((data) => {
            console.log(data)
          }).catch((error) => {
            console.error("Telegram Notification failed")
            console.error(error)
          })
